version: '3.8'

services:
  judge0:
    image: judge0/judge0:1.13.0
    volumes:
      - ./tmp/judge0:/tmp
    ports:
      - "2358:2358"
    privileged: true
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=YourPasswordHere
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=YourPasswordHere
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    restart: always

volumes:
  postgres_data: